name: CI-CD

on: 
  push:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install category_encoders streamlit
          pip install dvc[s3]

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: DVC Pull
        run: |
          dvc pull --force 

      - name: Run pipeline
        run: |
          dvc repro

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESSTOKEN }}

      - name: Build and Push Docker Image
        if: success()
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/spotify-music-recommender:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/spotify-music-recommender:latest
      
      - name: Deploy to AWS EC2
        if: success()
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSHKEY }}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/spotify-music-recommender:latest
            docker stop spotify-music-recommender || true
            docker rm spotify-music-recommender || true
            docker run -d -p 80:8501 --name spotify-music-recommender ${{ secrets.DOCKER_HUB_USERNAME }}/spotify-music-recommender:latest